exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-symlinks

  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        additional_dependencies: [
            # 'flake8-isort',
            'flake8-blind-except',
            'flake8-commas',
            'flake8-comprehensions',
            'flake8-deprecated',
            # "flake8-docstrings",
            'flake8-meiqia',
            'flake8-mutable',
            'flake8-pep3101',
            # "flake8-quotes",
            'flake8-string-format',
            'flake8-tidy-imports',
          ]

  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports']

  - repo: https://github.com/myint/docformatter.git
    rev: v1.4
    hooks:
      - id: docformatter
        args:
          ['--in-place', '--wrap-summaries=80', '--wrap-descriptions=80', '--pre-summary-newline']

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black