version: "3.8"

services:

  django:
    build: .
    # entrypoint: python manage.py runserver 0.0.0.0:8000
    environment:
      - ENVIRONMENT=dev
    restart: always
    volumes:
      - ./:/code/
    ports:
      - 8001:8000
    depends_on:
      - db
      - redis

  db:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - videochat_db:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    restart: always

volumes:
  videochat_db:
