# Generated by Django 3.2 on 2023-10-01 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roommember",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="roommember",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chat.room"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="reader",
            field=models.ManyToManyField(related_name="reader", to="chat.RoomMember"),
        ),
        migrations.AddField(
            model_name="message",
            name="room_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chat.roommember"
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="member",
            field=models.ManyToManyField(
                blank=True, related_name="member", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roommember",
            unique_together={("member", "room")},
        ),
        migrations.AlterUniqueTogether(
            name="contactrequest",
            unique_together={("sender", "receiver")},
        ),
    ]
